### ISSUE TITLE
SQL locked, backend closes following high CPU usage on unraid.

### ISSUE THREAD

**Issue by bambamalicious** [devedse/DeveLanCacheUI_Backend#38]
Snippet below from console. have removed all develancacheui files from server, removed and re-installed container and still error persists. Any help would be greatly appreciated.

`      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
         at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel, Boolean deferred)
         at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel, Boolean deferred)
         at System.Data.Common.DbConnection.BeginDbTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at DeveLanCacheUI_Backend.Steam.SteamDepotEnricherHostedService.<>c__DisplayClass7_0.<<GoRun>b__3>d.MoveNext() in /src/DeveLanCacheUI_Backend/Steam/SteamDepotEnricherHostedService.cs:line 164
      --- End of stack trace from previous location ---
         at DeveLanCacheUI_Backend.Steam.SteamDepotEnricherHostedService.<>c__DisplayClass7_0.<<GoRun>b__3>d.MoveNext() in /src/DeveLanCacheUI_Backend/Steam/SteamDepotEnricherHostedService.cs:line 167
      --- End of stack trace from previous location ---
         at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
         at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
         at DeveLanCacheUI_Backend.Steam.SteamDepotEnricherHostedService.GoRun(CancellationToken stoppingToken) in /src/DeveLanCacheUI_Backend/Steam/SteamDepotEnricherHostedService.cs:line 133
         at DeveLanCacheUI_Backend.Steam.SteamDepotEnricherHostedService.ExecuteAsync(CancellationToken stoppingToken) in /src/DeveLanCacheUI_Backend/Steam/SteamDepotEnricherHostedService.cs:line 29
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...`

**Comment by devedse** [comment]
Hello, this seems to be an issue with SQLite:
https://www.beekeeperstudio.io/blog/how-to-solve-sqlite-database-is-locked-error#:~:text=If%20you%20are%20encountering%20the%20%E2%80%9CSQLite%20database%20is%20locked%E2%80%9D%20error,has%20not%20been%20properly%20closed.

As the tool should go through the log file completely I'd say the easiest way is to just remove the database files and restart the container.
