### ISSUE TITLE
Latest update breaks front end use.

### ISSUE THREAD

**Issue by slimshizn** [devedse/DeveLanCacheUI_Backend#49]
Unhandled error when trying to view `Latest Downloads` and `Steam Latest Downloads`. `Download Stats` continues to work.

**Comment by devedse** [comment]
I'll try to look into this in the near future :)

**Comment by devedse** [comment]
@slimshizn 
Can you maybe share both the docker logs of the backend/frontend and the F12 console output in the browser?

**Comment by SilverDrag0n1** [comment]
> Unhandled error when trying to view `Latest Downloads`, `Steam Latest Downloads` and `Download Stats`.

Hi all, I recently installed DeveLanCacheUI_frontend and backend on unraid but get the same error, I've never used it before its quite new for me.
Has there been any updates on this error?

**Comment by devedse** [comment]
If you want we should probably meet on discord or so to investigate what's going wrong. Else it kinda remains a guessing game.

**Comment by devedse** [comment]
What you can also try is remove your database and let the backend re-run through your logs.

**Comment by C0NTi** [comment]
I was having the exact same issues as 'slimshizn' - Only download stats working

I tried the suggestion of reverting to a 1.0.90 version and it worked immediately. So thanks @slimshizn for the temp workaround

**Comment by SilverDrag0n1** [comment]
> What you can also try is remove your database and let the backend re-run through your logs.

Sorry it's taken me awhile to reply, I tried to do this but got lost, where is the database located.
I also tried deleting it and running 1.0.9 but it didn't work for me.

**Comment by devedse** [comment]
> > What you can also try is remove your database and let the backend re-run through your logs.
> 
> Sorry it's taken me awhile to reply, I tried to do this but got lost, where is the database located. I also tried deleting it and running 1.0.9 but it didn't work for me.

The database is located here:
![image](https://github.com/user-attachments/assets/fc5c0644-8d78-4c48-8fff-b8e3504cadd8)

If you first stop the container, then throw that away, it should then re-read all the logs and recreate the database.

**Comment by SilverDrag0n1** [comment]
Awesome I will see if I can find that - I run unraid and this is what i can see in where the files are located.
![image](https://github.com/user-attachments/assets/9d0b8db7-3c45-46d4-bfb0-db15e833a52a)
I've looked in "depotdir" but that's an empty folder - is there another way to locate that folder?

**Comment by mkulina** [comment]
I am also on unraid and only download stats load. 

![image](https://github.com/user-attachments/assets/d0800b3c-23df-4d06-89e4-0ce77669f8ed)


![image](https://github.com/user-attachments/assets/e6fa132e-e239-4ee5-b213-7ebd518cbeca)

**Comment by devedse** [comment]
Hmm it's an error about CORS.

Can you click on the link in the error and see if that works?

**Comment by mkulina** [comment]
@devedse Just reproduces the 500. 
![image](https://github.com/user-attachments/assets/ef66d14c-f54a-4fe6-988a-ebec95c69471)

**Comment by devedse** [comment]
What do the docket logs show at this point?

**Comment by mkulina** [comment]
Here is what I see when I click the logs in docker to open a window in unraid.

`fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN6EJGRNKLUA", Request id "0HN6EJGRNKLUA:00000006": An unhandled exception was thrown by the application.
      System.ArgumentException: An item with the same key has already been added. Key: 17020
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
         at DeveLanCacheUI_Backend.Services.OriginalDepotEnricher.SteamApi.<>c.<.cctor>b__7_0() in /src/DeveLanCacheUI_Backend/Services/OriginalDepotEnricher/SteamApi.cs:line 5
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
      --- End of stack trace from previous location ---
         at System.Lazy`1.CreateValue()
         at DeveLanCacheUI_Backend.Services.OriginalDepotEnricher.SteamApi.get_SteamAppDict() in /src/DeveLanCacheUI_Backend/Services/OriginalDepotEnricher/SteamApi.cs:line 9
         at DeveLanCacheUI_Backend.Services.OriginalDepotEnricher.OriginalSteamAppObtainerService.GetSteamAppById(Nullable`1 steamAppId) in /src/DeveLanCacheUI_Backend/Services/OriginalDepotEnricher/OriginalSteamAppObtainerService.cs:line 7
         at DeveLanCacheUI_Backend.Controllers.DownloadEventsController.<>c__DisplayClass6_0.<GetFilteredBySkipAndCountInternal>b__12(IGrouping`2 group) in /src/DeveLanCacheUI_Backend/Controllers/DownloadEventsController.cs:line 90
         at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
         at DeveLanCacheUI_Backend.Controllers.DownloadEventsController.GetFilteredBySkipAndCountInternal(Int32 skip, Int32 count, String filter) in /src/DeveLanCacheUI_Backend/Controllers/DownloadEventsController.cs:line 62
         at lambda_method270(Closure, Object)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN6EJGRNKLUA", Request id "0HN6EJGRNKLUA:00000007": An unhandled exception was thrown by the application.
      System.ArgumentException: An item with the same key has already been added. Key: 17020
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
         at DeveLanCacheUI_Backend.Services.OriginalDepotEnricher.SteamApi.<>c.<.cctor>b__7_0() in /src/DeveLanCacheUI_Backend/Services/OriginalDepotEnricher/SteamApi.cs:line 5
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
      --- End of stack trace from previous location ---
         at System.Lazy`1.CreateValue()
         at DeveLanCacheUI_Backend.Services.OriginalDepotEnricher.SteamApi.get_SteamAppDict() in /src/DeveLanCacheUI_Backend/Services/OriginalDepotEnricher/SteamApi.cs:line 9
         at DeveLanCacheUI_Backend.Services.OriginalDepotEnricher.OriginalSteamAppObtainerService.GetSteamAppById(Nullable`1 steamAppId) in /src/DeveLanCacheUI_Backend/Services/OriginalDepotEnricher/OriginalSteamAppObtainerService.cs:line 7
         at DeveLanCacheUI_Backend.Controllers.DownloadEventsController.<>c__DisplayClass6_0.<GetFilteredBySkipAndCountInternal>b__12(IGrouping`2 group) in /src/DeveLanCacheUI_Backend/Controllers/DownloadEventsController.cs:line 90
         at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
         at DeveLanCacheUI_Backend.Controllers.DownloadEventsController.GetFilteredBySkipAndCountInternal(Int32 skip, Int32 count, String filter) in /src/DeveLanCacheUI_Backend/Controllers/DownloadEventsController.cs:line 62
         at lambda_method280(Closure, Object)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: DeveLanCacheUI_Backend.LogReading.LanCacheLogReaderHostedService[0]
      09/07/2024 18:06:46 No new log lines, waiting...`

**Comment by C0NTi** [comment]
I added the following to my docker compose

environment:
      - AllowedHosts=*

now it works fine. I was also getting the cors error

**Comment by mkulina** [comment]
> I added the following to my docker compose
> 
> environment: - AllowedHosts=*
> 
> now it works fine. I was also getting the cors error

This resolved it for me as well!

**Comment by devedse** [comment]
Sick shit guys, I'll add it to the readme :smile:
