### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added. Key: 

### ISSUE THREAD

**Issue by rossdargan** [devedse/DeveLanCacheUI_Backend#57]
Clicking to view the steam apps gives me this error in the logs. Let me know if you want a hand figuring it out!
```
lancache-develancacheui_backend-1   | info: DeveLanCacheUI_Backend.Controllers.StatusController[0]
lancache-develancacheui_backend-1   |       ### Status Controller Get() called
lancache-develancacheui_backend-1   | fail: Microsoft.AspNetCore.Server.Kestrel[13]
lancache-develancacheui_backend-1   |       Connection id "0HN7S03VJ6JH2", Request id "0HN7S03VJ6JH2:0000000C": An unhandled exception was thrown by the application.
lancache-develancacheui_backend-1   |       System.ArgumentException: An item with the same key has already been added. Key: 2811380
lancache-develancacheui_backend-1   |          at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
lancache-develancacheui_backend-1   |          at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
lancache-develancacheui_backend-1   |          at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
lancache-develancacheui_backend-1   |          at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
lancache-develancacheui_backend-1   |          at DeveLanCacheUI_Backend.Services.OriginalDepotEnricher.SteamApi.<>c.<.cctor>b__7_0() in /src/DeveLanCacheUI_Backend/Services/OriginalDepotEnricher/SteamApi.cs:line 5
lancache-develancacheui_backend-1   |          at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
lancache-develancacheui_backend-1   |       --- End of stack trace from previous location ---
lancache-develancacheui_frontend-1  | 192.168.86.203 - - [03/Nov/2024:12:15:01 +0000] "GET /DeveLanCacheUI.png HTTP/1.1" 200 3348 "http://192.168.86.56:7302/latestdownloads" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0" "-"
lancache-develancacheui_frontend-1  | 192.168.86.203 - - [03/Nov/2024:12:15:01 +0000] "GET /css/open-iconic/font/fonts/open-iconic.woff HTTP/1.1" 200 14984 "http://192.168.86.56:7302/css/open-iconic/font/css/open-iconic-bootstrap.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0" "-"
lancache-develancacheui_backend-1   |          at System.Lazy`1.CreateValue()
lancache-develancacheui_backend-1   |          at DeveLanCacheUI_Backend.Services.OriginalDepotEnricher.SteamApi.get_SteamAppDict() in /src/DeveLanCacheUI_Backend/Services/OriginalDepotEnricher/SteamApi.cs:line 9
lancache-develancacheui_backend-1   |          at DeveLanCacheUI_Backend.Services.OriginalDepotEnricher.OriginalSteamAppObtainerService.GetSteamAppById(Nullable`1 steamAppId) in /src/DeveLanCacheUI_Backend/Services/OriginalDepotEnricher/OriginalSteamAppObtainerService.cs:line 7
lancache-develancacheui_backend-1   |          at DeveLanCacheUI_Backend.Controllers.DownloadEventsController.<>c__DisplayClass6_0.<GetFilteredBySkipAndCountInternal>b__12(IGrouping`2 group) in /src/DeveLanCacheUI_Backend/Controllers/DownloadEventsController.cs:line 90
lancache-develancacheui_backend-1   |          at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
lancache-develancacheui_backend-1   |          at DeveLanCacheUI_Backend.Controllers.DownloadEventsController.GetFilteredBySkipAndCountInternal(Int32 skip, Int32 count, String filter) in /src/DeveLanCacheUI_Backend/Controllers/DownloadEventsController.cs:line 62
lancache-develancacheui_backend-1   |          at lambda_method207(Closure, Object)
lancache-develancacheui_backend-1   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
lancache-develancacheui_backend-1   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
lancache-develancacheui_backend-1   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
lancache-develancacheui_backend-1   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
lancache-develancacheui_backend-1   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
lancache-develancacheui_backend-1   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
lancache-develancacheui_backend-1   |       --- End of stack trace from previous location ---
lancache-develancacheui_backend-1   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
lancache-develancacheui_backend-1   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
lancache-develancacheui_backend-1   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
lancache-develancacheui_backend-1   |          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
lancache-develancacheui_backend-1   |          at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
lancache-develancacheui_backend-1   |          at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
lancache-develancacheui_backend-1   |          at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
lancache-develancacheui_backend-1   |          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
lancache-develancacheui_backend-1   |          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by SleeperXr** [comment]
Have the same Problem, even completely erased all of my lancache and appdata Files from Backend and Frontend

`  ### Status Controller Get() called
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN9DSUAQE62R", Request id "0HN9DSUAQE62R:00000001": An unhandled exception was thrown by the application.
      System.ArgumentException: An item with the same key has already been added. Key: 3315270
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at System.Linq.Enumerable.SpanToDictionary[TSource,TKey,TElement](ReadOnlySpan`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
         at DeveLanCacheUI_Backend.Services.OriginalDepotEnricher.SteamApi.<>c.<.cctor>b__7_0() in /src/DeveLanCacheUI_Backend/Services/OriginalDepotEnricher/SteamApi.cs:line 5
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
      --- End of stack trace from previous location ---
         at System.LazyHelper.ThrowException()
         at System.Lazy`1.CreateValue()
         at DeveLanCacheUI_Backend.Services.OriginalDepotEnricher.SteamApi.get_SteamAppDict() in /src/DeveLanCacheUI_Backend/Services/OriginalDepotEnricher/SteamApi.cs:line 9
         at DeveLanCacheUI_Backend.Services.OriginalDepotEnricher.OriginalSteamAppObtainerService.GetSteamAppById(Nullable`1 steamAppId) in /src/DeveLanCacheUI_Backend/Services/OriginalDepotEnricher/OriginalSteamAppObtainerService.cs:line 7
         at DeveLanCacheUI_Backend.Controllers.DownloadEventsController.<>c__DisplayClass6_0.<GetFilteredBySkipAndCountInternal>b__12(IGrouping`2 group) in /src/DeveLanCacheUI_Backend/Controllers/DownloadEventsController.cs:line 90
         at System.Linq.Enumerable.IteratorSelectIterator`2.ToListNoPresizing()
         at System.Linq.Enumerable.IteratorSelectIterator`2.ToList()
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
         at DeveLanCacheUI_Backend.Controllers.DownloadEventsController.GetFilteredBySkipAndCountInternal(Int32 skip, Int32 count, String filter) in /src/DeveLanCacheUI_Backend/Controllers/DownloadEventsController.cs:line 62
         at lambda_method235(Closure, Object)
         at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: DeveLanCacheUI_Backend.LogReading.LanCacheLogReaderHostedService[0]
      01/06/2025 00:19:29 No new log lines, waiting...
info: DeveLanCacheUI_Backend.LogReading.LanCacheLogReaderHostedService[0]
      Processing 1 lines... First DateTime: 01/06/2025 00:19:57 (Total processed: 676730)`
